### ISSUE TITLE
IllegalArgumentException when importing ARM7

### ISSUE THREAD

**Issue by LRFLEW** [pedro-javierf/NTRGhidra#8]
**Describe the bug**
I was using this extension to disassemble Rhythm Heaven (YLZE01). When I tried to import the ARM7 code for the game, an exception occurred during the import. If I try to open the imported file, the project is empty.

**To Reproduce**
1. Add the Rhythm Heaven ROM to Ghidra
2. On the NTRGhidra dialogs, select ARM7
3. Note the stack trace under "Additional Information"

**Expected behavior**
The code is actually imported.

**Stack Trace**
```
Invalid block name: ARM7 Main Memory
java.lang.IllegalArgumentException: Invalid block name: ARM7 Main Memory
	at ghidra.program.database.mem.MemoryMapDB.checkBlockName(MemoryMapDB.java:821)
	at ghidra.program.database.mem.MemoryMapDB.createInitializedBlock(MemoryMapDB.java:600)
	at ghidra.program.database.mem.MemoryMapDB.createInitializedBlock(MemoryMapDB.java:571)
	at ntrghidra.NTRGhidraLoader.load(NTRGhidraLoader.java:273)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.doLoad(AbstractLibrarySupportLoader.java:347)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadProgram(AbstractLibrarySupportLoader.java:83)
	at ghidra.app.util.opinion.AbstractLibraryLoader.load(AbstractLibraryLoader.java:112)
	at ghidra.util.task.TaskLauncher$1.run(TaskLauncher.java:90)
	at ghidra.util.task.Task.monitoredRun(Task.java:124)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$1(TaskRunner.java:94)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

**My System:**
- OS: Windows 10 20H2
- Ghidra 9.2
- NTRGhidra 1.4.3

**Comment by pedro-javierf** [comment]
@LRFLEW thanks for opening an issue.

I have identified the problem and fixed it with commit ca3ff08643697590cf1330a0647cff689c3bafc0 which will make it to the next release as soon as possible. 

This was an issue related to the last Ghidra update, which changed what "valid region names" were considered (forbidding blank spaces)
